version: '3.8'
services:
  nginx:
    container_name: ngix 
    build:
      context: ./requirements/ngix
      dockerfile: dockerfile 
    networks:
      - Inception-net 
    depends_on:
      - wordpress
    ports:
      -"443:443"
    volumes:
      -data:/var/www/html
    


