version: '3.8'
services:
  nginx:
    container_name: ngix 
    build:
      context: ./requirements/ngix
      image: nginx
    networks:
      - Inception-net 
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - data_file:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      image: wordpress 
      expose:
        "9000"
      network:
        - Inception-net 
    volumes:
      - data_file:/var/www/html
    networks:
      - Inception
    depends_on:
      - mariadb
    restart: always
  