version: '3.8'
services:
  nginx:
    container_name: ngix 
    build:
      context: ./requirements/ngix
      dockerfile: dockerfile 
    networks:
      - Inception-net 
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - data_file:/var/www/html
  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: 
      expose:
        "9000"
      network:
        - Inception-net 
    volumes:
      - data_file:/var/www/html
      